import { useRouter } from 'next/router'

const Home = () => {
  return (
    <div className="bg-gray-500">
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"></link>

      <main>
        <div className="flex flex-col border border-black">
          <div className="text-center py-2 m-2">
            <p className="text-3xl">ログイン</p>
          </div>
          <div className="text-center py-2 m-2">
            <form>
              <label>
                <input className="border border-black text" name="id/mail"/>
              </label>
            </form>
          </div>
          <div className="text-center py-2 m-2">
            <form>
              <label>
                <input className="border border-black text" name="pass" />
              </label>
            </form>
          </div>
          <div className="text-center py-2 m-2">
            
            <h1 className="title">
                <button className="px-2 py-1  bg-red-500 text-lg text-white rounded-full">ログイン</button>
            </h1>
          </div>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;
